

```{r load-data}
ahrf_2019_2020 <- read.csv("D:/data science 2/data_science_2/data/ahrf_2019_2020_maine.csv")
ahrf_2020_2021 <- read.csv("D:/data science 2/data_science_2/data/ahrf_2020_2021_maine.csv")
ahrf_2021_2022 <- read.csv("D:/data science 2/data_science_2/data/ahrf_2021_2022_maine.csv")
ahrf_2022_2023 <- read.csv("D:/data science 2/data_science_2/data/ahrf_2022_2023_maine.csv")
ahrf_2019_2023 <- read.csv("D:/data science 2/data_science_2/data/ahrf_2019_2023.csv")
```

```{r maine-population}
maine_pop <- ahrf_2022_2023 %>% 
  select(cnty_name, cens_popn_20, cens_popn_10)
```

```{r}
ahrf_with_census <- ahrf_2019_2023 %>% 
  left_join(y = maine_pop, by = c("county_name" = "cnty_name"))
```

```{r md_counts-select}
prelim_md_count <- ahrf_2019_2023 %>% 
  select(county_name, md_nf_all_gp_21, md_nf_all_gp_20, md_nf_all_gp_19,	md_nf_all_gp_18, md_nf_all_gp_15,	md_nf_all_gp_10, 
         md_nf_fammed_gen_21, md_nf_fammed_gen_20,	md_nf_fammed_gen_19, md_nf_fammed_gen_18, md_nf_fammed_gen_15,	md_nf_fammed_gen_10,
         md_nf_all_med_spec_21, md_nf_all_med_spec_20, md_nf_all_med_spec_19,	md_nf_all_med_spec_18,	md_nf_all_med_spec_15, md_nf_all_med_spec_10,
         md_nf_allergy_21,	md_nf_allergy_20,	md_nf_allergy_19,	md_nf_allergy_18,	md_nf_allergy_15,	md_nf_allergy_10, 
         md_nf_card_dis_21, md_nf_card_dis_20,	md_nf_card_dis_19,	md_nf_card_dis_18, md_nf_card_dis_15, md_nf_card_dis_10, 
         md_nf_derm_21,	md_nf_derm_20, md_nf_derm_19,	md_nf_derm_18, md_nf_derm_15, md_nf_derm_10, 
         md_nf_gastr_21, md_nf_gastr_20, md_nf_gastr_19, md_nf_gastr_18,	md_nf_gastr_15, md_nf_gastr_10, 
         md_nf_genintmed_21,	md_nf_genintmed_20,	md_nf_genintmed_19,	md_nf_genintmed_18,	md_nf_genintmed_15,	md_nf_genintmed_10, 
         md_nf_ped_gen_21, md_nf_ped_gen_20,	md_nf_ped_gen_19,	md_nf_ped_gen_18,	md_nf_ped_gen_15,	md_nf_ped_gen_10, 
         md_nf_all_surg_spec_21,	md_nf_all_surg_spec_20,	md_nf_all_surg_spec_19,	md_nf_all_surg_spec_18,	md_nf_all_surg_spec_15,	md_nf_all_surg_spec_10,
         md_nf_gen_surg_21, md_nf_gen_surg_20,	md_nf_gen_surg_19, md_nf_gen_surg_18,	md_nf_gen_surg_15, md_nf_gen_surg_10, 
         md_nf_obgyn_gen_21,	md_nf_obgyn_gen_20,	md_nf_obgyn_gen_19,	md_nf_obgyn_gen_18,	md_nf_obgyn_gen_15,	md_nf_obgyn_gen_10, 
         md_nf_ophth_21,	md_nf_ophth_20,	md_nf_ophth_19, md_nf_ophth_18,	md_nf_ophth_15,	md_nf_ophth_10, 
         md_nf_anesth_21, md_nf_anesth_20,	md_nf_anesth_19,	md_nf_anesth_18, md_nf_anesth_15,	md_nf_anesth_10, 
         md_nf_child_psych_21, md_nf_child_psych_20,	md_nf_child_psych_19,	md_nf_child_psych_18,	md_nf_child_psych_15,	md_nf_child_psych_10,
         md_nf_emerg_med_21,	md_nf_emerg_med_20,	md_nf_emerg_med_19,	md_nf_emerg_med_18,	md_nf_emerg_med_15,	md_nf_emerg_med_10, md_nf_neuro_21,
         md_nf_neuro_20, md_nf_neuro_19,	md_nf_neuro_18,	md_nf_neuro_15,	md_nf_neuro_10, 
         md_nf_psych_21,	md_nf_psych_20,	md_nf_psych_19,	md_nf_psych_18,	md_nf_psych_15,	md_nf_psych_10)
```

```{r md-count-pivots, warning = FALSE}
prelim_fammed_md_count <- prelim_md_count %>% 
  pivot_longer(starts_with("md_nf_fammed_gen"), names_to = "md_fammed_year", values_to = "md_fammed_count", names_prefix = "md_nf_fammed_gen_") %>% 
  mutate(md_fammed_year = as.numeric(md_fammed_year) + 2000) %>% 
  select(county_name, md_fammed_year, md_fammed_count) %>% 
  drop_na(md_fammed_year, md_fammed_count) %>% 
  distinct(county_name, md_fammed_year, .keep_all = TRUE)
  
prelim_spec_md_count <- prelim_md_count %>%   
  pivot_longer(starts_with("md_nf_all_med_spec"), names_to = "md_spec_year", values_to = "md_spec_count", names_prefix = "md_nf_all_med_spec_") %>% 
  mutate(md_spec_year = as.numeric(md_spec_year) + 2000) %>% 
  select(county_name, md_spec_year, md_spec_count) %>% 
  drop_na(md_spec_year, md_spec_count) %>% 
  distinct(county_name, md_spec_year, .keep_all = TRUE)
  
prelim_allergy_md_count <- prelim_md_count %>% 
  pivot_longer(starts_with("md_nf_allergy"), names_to = "md_allergy_year", values_to = "md_allergy_count", names_prefix = "md_nf_allergy_") %>% 
  mutate(md_allergy_year = as.numeric(md_allergy_year) + 2000) %>%  
  select(county_name, md_allergy_year, md_allergy_count) %>% 
  drop_na(md_allergy_year, md_allergy_count) %>% 
  distinct(county_name, md_allergy_year, .keep_all = TRUE)
  
prelim_card_md_count <- prelim_md_count %>% 
  pivot_longer(starts_with("md_nf_card_dis"), names_to = "md_card_year", values_to = "md_card_count", names_prefix = "md_nf_card_dis_") %>% 
  mutate(md_card_year = as.numeric(md_card_year) + 2000) %>% 
  select(county_name, md_card_year, md_card_count) %>% 
  drop_na(md_card_year, md_card_count) %>% 
  distinct(county_name, md_card_year, .keep_all = TRUE)
  
prelim_derm_md_count <- prelim_md_count %>%   
  pivot_longer(starts_with("md_nf_derm"), names_to = "md_derm_year", values_to = "md_derm_count", names_prefix = "md_nf_derm_") %>% 
  mutate(md_derm_year = as.numeric(md_derm_year) + 2000) %>% 
  select(county_name, md_derm_year, md_derm_count) %>% 
  drop_na(md_derm_year, md_derm_count) %>% 
  distinct(county_name, md_derm_year, .keep_all = TRUE)

prelim_gastr_md_count <- prelim_md_count %>%   
  pivot_longer(starts_with("md_nf_gastr"), names_to = "md_gastr_year", values_to = "md_gastr_count", names_prefix = "md_nf_gastr_") %>% 
  mutate(md_gastr_year = as.numeric(md_gastr_year) + 2000) %>% 
  select(county_name, md_gastr_year, md_gastr_count) %>% 
  drop_na(md_gastr_year, md_gastr_count) %>% 
  distinct(county_name, md_gastr_year, .keep_all = TRUE)
  
prelim_genint_md_count <- prelim_md_count %>% 
  pivot_longer(starts_with("md_nf_genintmed"), names_to = "md_genintmed_year", values_to = "md_genintmed_count", names_prefix = "md_nf_genintmed_") %>% 
  mutate(md_genintmed_year = as.numeric(md_genintmed_year) + 2000) %>% 
  select(county_name, md_genintmed_year, md_genintmed_count) %>% 
  drop_na(md_genintmed_year, md_genintmed_count) %>% 
  distinct(county_name, md_genintmed_year, .keep_all = TRUE)

prelim_surgspec_md_count <- prelim_md_count %>% 
  pivot_longer(starts_with("md_nf_all_surg_spec"), names_to = "md_surg_spec_year", values_to = "md_surg_spec_count", names_prefix = "md_nf_all_surg_spec_") %>% 
  mutate(md_surg_spec_year = as.numeric(md_surg_spec_year) + 2000) %>% 
  select(county_name, md_surg_spec_year, md_surg_spec_count) %>% 
  drop_na(md_surg_spec_year, md_surg_spec_count) %>% 
  distinct(county_name, md_surg_spec_year, .keep_all = TRUE)

prelim_gensurg_md_count <- prelim_md_count %>% 
  pivot_longer(starts_with("md_nf_gen_surg"), names_to = "md_gen_surg_year", values_to = "md_gen_surg_count", names_prefix = "md_nf_gen_surg_") %>% 
  mutate(md_gen_surg_year = as.numeric(md_gen_surg_year) + 2000) %>% 
  select(county_name, md_gen_surg_year, md_gen_surg_count) %>% 
  drop_na(md_gen_surg_year, md_gen_surg_count) %>% 
  distinct(county_name, md_gen_surg_year, .keep_all = TRUE)

prelim_ob_md_count <- prelim_md_count %>%   
  pivot_longer(starts_with("md_nf_obgyn_gen"), names_to = "md_obgyn_year", values_to = "md_obgyn_count", names_prefix = "md_nf_obgyn_gen_") %>% 
  mutate(md_obgyn_year = as.numeric(md_obgyn_year) + 2000) %>% 
  select(county_name, md_obgyn_year, md_obgyn_count) %>% 
  drop_na(md_obgyn_year, md_obgyn_count) %>% 
  distinct(county_name, md_obgyn_year, .keep_all = TRUE)

prelim_ophth_md_count <- prelim_md_count %>% 
  pivot_longer(starts_with("md_nf_ophth"), names_to = "md_ophth_year", values_to = "md_ophth_count", names_prefix = "md_nf_ophth_") %>% 
  mutate(md_ophth_year = as.numeric(md_ophth_year) + 2000) %>% 
  select(county_name, md_ophth_year, md_ophth_count) %>% 
  drop_na(md_ophth_year, md_ophth_count) %>% 
  distinct(county_name, md_ophth_year, .keep_all = TRUE)

prelim_anesth_md_count <- prelim_md_count %>% 
  pivot_longer(starts_with("md_nf_anesth"), names_to = "md_anesth_year", values_to = "md_anesth_count", names_prefix = "md_nf_anesth_") %>% 
  mutate(md_anesth_year = as.numeric(md_anesth_year) + 2000) %>% 
  select(county_name, md_anesth_year, md_anesth_count) %>% 
  drop_na(md_anesth_year, md_anesth_count) %>% 
  distinct(county_name, md_anesth_year, .keep_all = TRUE)

prelim_emerg_md_count <- prelim_md_count %>% 
  pivot_longer(starts_with("md_nf_emerg_med"), names_to = "md_emerg_med_year", values_to = "md_emerg_med_count", names_prefix = "md_nf_emerg_med_") %>% 
  mutate(md_emerg_med_year = as.numeric(md_emerg_med_year) + 2000) %>% 
  select(county_name, md_emerg_med_year, md_emerg_med_count) %>% 
  drop_na(md_emerg_med_year, md_emerg_med_count) %>% 
  distinct(county_name, md_emerg_med_year, .keep_all = TRUE)

prelim_neuro_md_count <- prelim_md_count %>% 
  pivot_longer(starts_with("md_nf_neuro"), names_to = "md_neuro_year", values_to = "md_neuro_count", names_prefix = "md_nf_neuro_") %>% 
  mutate(md_neuro_year = as.numeric(md_neuro_year) + 2000) %>% 
  select(county_name, md_neuro_year, md_neuro_count) %>% 
  drop_na(md_neuro_year, md_neuro_count) %>% 
  distinct(county_name, md_neuro_year, .keep_all = TRUE)

prelim_psych_md_count <- prelim_md_count %>%   
  pivot_longer(starts_with("md_nf_psych"), names_to = "md_psych_year", values_to = "md_psych_count", names_prefix = "md_nf_psych_") %>% 
  mutate(md_psych_year = as.numeric(md_psych_year)) %>%
  select(county_name, md_psych_year, md_psych_count) %>% 
  drop_na(md_psych_year, md_psych_count) %>% 
  distinct(county_name, md_psych_year, .keep_all = TRUE)
```

```{r md-count-BROKEN-CODE-JAIL}
# prelim_all_md_count <- prelim_md_count %>% 
#   pivot_longer(starts_with("md_nf_all_gp"), names_to = "all_gp_md_year", values_to = "all_gp_md_count", names_prefix = "md_nf_all_gp") %>% 
#   mutate(all_gp_md_year = as.numeric(all_gp_md_year) + 2000) %>% 
#   select(county_name, all_gp_md_year, all_gp_md_count) %>% 
#   drop_na(all_gp_md_year, all_gp_md_count) %>% 
#   distinct(county_name, all_gp_md_year, .keep_all = TRUE)
# 
# prelim_ped_md_count <- prelim_md_count %>%   
#   pivot_longer(starts_with("md_nf_ped_gen"), names_to = "md_gen_ped_year", values_to = "md_gen_ped_count", names_prefix = "md_ng_ped_gen_") %>% 
#   mutate(md_gen_ped_year = as.numeric(md_gen_ped_year) + 2000) %>% 
#   select(county_name, md_gen_ped_year, md_gen_ped_count) %>% 
#   drop_na(md_gen_ped_year, md_gen_ped_count) %>% 
#   distinct(county_name, md_gen_ped_year, .keep_all = TRUE)
# 
# prelim_child_psych_md_count <- prelim_md_count %>%   
#   pivot_longer(starts_with("md_nf_child_psych"), names_to = "md_child_psych_year", values_to = "md_child_psych_count", names_prefix = "md_nf_child_psych") %>% 
#   mutate(md_child_psych_year = as.numeric(md_child_psych_year) + 2000) %>% 
#   select(county_name, md_child_psych_year, md_child_psych_count) %>% 
#   drop_na(md_child_psych_year, md_child_psych_count) %>% 
#   distinct(county_name, md_child_psych_year, .keep_all = TRUE)
```


```{r bind-md-counts}
# Missing all md, child psych, and pediatric. in broken code jail. 
md_counts <- prelim_allergy_md_count %>% 
  bind_cols(prelim_anesth_md_count) %>% 
  bind_cols(prelim_card_md_count) %>% 
  bind_cols(prelim_derm_md_count) %>% 
  bind_cols(prelim_emerg_md_count) %>% 
  bind_cols(prelim_fammed_md_count) %>% 
  bind_cols(prelim_gastr_md_count) %>% 
  bind_cols(prelim_genint_md_count) %>% 
  bind_cols(prelim_gensurg_md_count) %>% 
  bind_cols(prelim_neuro_md_count) %>% 
  bind_cols(prelim_ob_md_count) %>% 
  bind_cols(prelim_ophth_md_count) %>% 
  bind_cols(prelim_psych_md_count) %>% 
  bind_cols(prelim_spec_md_count) %>% 
  bind_cols(prelim_surgspec_md_count) %>% 
  select(county_name...1, md_allergy_year, md_allergy_count, md_anesth_count, md_card_count, md_derm_count, md_emerg_med_count, md_fammed_count,  md_gastr_count, md_genintmed_count, md_gen_surg_count, md_neuro_count, md_obgyn_count, md_ophth_count, md_psych_count, md_spec_count, md_surg_spec_count) %>% 
  rename(county_name = county_name...1,
         count_year = md_allergy_year)

write.csv(md_counts, "D:/data science 2/data_science_2/data/md_counts.csv")
```



